name: NPM SCA

on:
  push:
    branches: [ main ]


jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run linting rules and tests
        uses: actions/setup-node@v3
        with:
          node-version: '21.5.0'
      - run: pwd
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'todo-app'
          path: '.'
          # format: 'JSON'
          format: 'SARIF'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --prettyPrint
      - name: Upload Test results
        uses: actions/upload-artifact@v4
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports/dependency-check-report.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
            sarif_file: reports/dependency-check-report.sarif
          # sarif_file: snyk.sarif
          # sarif_file: ${{github.workspace}}/reports/dependency-check-report.sarif
          # sarif_file: /github/workspace/reports/dependency-check-report.sarif
      # - name: Adding markdown
      #   run: echo '### Hello world! 🚀' >> $GITHUB_STEP_SUMMARY